//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UwizardWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte Language
        {
            get
            {
                return ((byte)(this["Language"]));
            }
            set
            {
                this["Language"] = value;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection GameFileFolderList
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameFileFolderList"]));
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://art.gametdb.com/wiiu/coverHQ/</string>
  <string>http://art.gametdb.com/wiiu/coverM/</string>
  <string>http://art.gametdb.com/wiiu/cover/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameTDBCoverFront
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameTDBCoverFront"]));
            }
            set
            {
                this["GameTDBCoverFront"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>http://art.gametdb.com/wiiu/cover3D/</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameTDBCover3D
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameTDBCover3D"]));
            }
            set
            {
                this["GameTDBCover3D"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://art.gametdb.com/wiiu/coverfullHQ/</string>
  <string>http://art.gametdb.com/wiiu/coverfullM/</string>
  <string>http://art.gametdb.com/wiiu/coverfull/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameTDBCoverFull
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameTDBCoverFull"]));
            }
            set
            {
                this["GameTDBCoverFull"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>http://art.gametdb.com/wiiu/discHQ/</string>
  <string>http://art.gametdb.com/wiiu/discM/</string>
  <string>http://art.gametdb.com/wiiu/disc/</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GameTDBCoverDisc
        {
            get
            {
                return ((global::System.Collections.Specialized.StringCollection)(this["GameTDBCoverDisc"]));
            }
            set
            {
                this["GameTDBCoverDisc"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAncastStarbuckKey
        {
            get
            {
                return ((string)(this["UserAncastStarbuckKey"]));
            }
            set
            {
                this["UserAncastStarbuckKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAncastEspressoKey
        {
            get
            {
                return ((string)(this["UserAncastEspressoKey"]));
            }
            set
            {
                this["UserAncastEspressoKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCommonKey
        {
            get
            {
                return ((string)(this["UserCommonKey"]));
            }
            set
            {
                this["UserCommonKey"] = value;
            }
        }
    }
}
