//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uwizard.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Uwizard.Resources.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Uwizard.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files|*.*.
        /// </summary>
        internal static string AllFileType {
            get {
                return ResourceManager.GetString("AllFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Manager.
        /// </summary>
        internal static string ArchiveManager {
            get {
                return ResourceManager.GetString("ArchiveManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL: Australia.
        /// </summary>
        internal static string AUS {
            get {
                return ResourceManager.GetString("AUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary &amp; Text Files|*.bin;*.txt.
        /// </summary>
        internal static string BinaryFileType {
            get {
                return ResourceManager.GetString("BinaryFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        internal static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon!.
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U Common Key.
        /// </summary>
        internal static string CommonKey {
            get {
                return ResourceManager.GetString("CommonKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The common key is invalid..
        /// </summary>
        internal static string CommonKeyInvalid {
            get {
                return ResourceManager.GetString("CommonKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The common key is required to decrypt the data..
        /// </summary>
        internal static string CommonKeyRequired {
            get {
                return ResourceManager.GetString("CommonKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of Uwizard available. Do you want to update from {0} to {1} ?.
        /// </summary>
        internal static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Contents.
        /// </summary>
        internal static string ContentCount {
            get {
                return ResourceManager.GetString("ContentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Contents.
        /// </summary>
        internal static string ContentDecrypt {
            get {
                return ResourceManager.GetString("ContentDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Content #{0} of {1} failed....
        /// </summary>
        internal static string ContentDownloadFailed {
            get {
                return ResourceManager.GetString("ContentDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Content #{0} of {1}... ({2} bytes) to.
        /// </summary>
        internal static string ContentDownloadTo {
            get {
                return ResourceManager.GetString("ContentDownloadTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting.
        /// </summary>
        internal static string ConvertError {
            get {
                return ResourceManager.GetString("ConvertError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2015 Mysteriosoft.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt version file at wiiubrew.net!.
        /// </summary>
        internal static string CorruptVersionFile {
            get {
                return ResourceManager.GetString("CorruptVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Folder List.
        /// </summary>
        internal static string CreateFolderList {
            get {
                return ResourceManager.GetString("CreateFolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits:\r\n  Mr. Mysterio - Programmer of Uwizard\r\n  Crediar - Programmer of DiscU and CDecrypt\r\n  MasterF0x - Distributor of BFSTM Decoder\r\n  GameTDB - Game Covers\r\n  VinsCool, capito27, phanteon, send0r - Translation\r\n\r\nChangeLog:\r\n  v1.1.3\r\n    German language added. \r\n    Spanish language added.\r\n    Minor bug fixes.\r\n\r\n  v1.1.2\r\n    BFWAV decoder added.\r\n    MP3 compiler added.\r\n\r\n  v1.1.1\r\n    SZS and SARC archive management added.\r\n    BFSTM multi-select and optio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting contents....
        /// </summary>
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decrypting contents!.
        /// </summary>
        internal static string DecryptingError {
            get {
                return ResourceManager.GetString("DecryptingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished decrypting contents..
        /// </summary>
        internal static string DecryptingSuccess {
            get {
                return ResourceManager.GetString("DecryptingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a folder to the list above. All Wii U games within that folder will be displayed in the list above..
        /// </summary>
        internal static string DirectoryAdd {
            get {
                return ResourceManager.GetString("DirectoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This removes all directories from the list displayed above. The games themselves are not deleted..
        /// </summary>
        internal static string DirectoryRemoveAll {
            get {
                return ResourceManager.GetString("DirectoryRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc title key is invalid..
        /// </summary>
        internal static string DiskTitleKeyInvalid {
            get {
                return ResourceManager.GetString("DiskTitleKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The disc title key is required to decrypt the data..
        /// </summary>
        internal static string DiskTitleKeyRequired {
            get {
                return ResourceManager.GetString("DiskTitleKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowloading.
        /// </summary>
        internal static string Dowloading {
            get {
                return ResourceManager.GetString("Dowloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download operation has been canceled..
        /// </summary>
        internal static string DownloadCancel {
            get {
                return ResourceManager.GetString("DownloadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed:.
        /// </summary>
        internal static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Download.
        /// </summary>
        internal static string DownloadStart {
            get {
                return ResourceManager.GetString("DownloadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Download.
        /// </summary>
        internal static string DownloadStop {
            get {
                return ResourceManager.GetString("DownloadStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Game Name.
        /// </summary>
        internal static string EnterGameName {
            get {
                return ResourceManager.GetString("EnterGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the name of the title to add..
        /// </summary>
        internal static string EnterTitleName {
            get {
                return ResourceManager.GetString("EnterTitleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Extracting Files!.
        /// </summary>
        internal static string ErrorExtracting {
            get {
                return ResourceManager.GetString("ErrorExtracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U Espresso Ancast Key.
        /// </summary>
        internal static string EspressoAncastKey {
            get {
                return ResourceManager.GetString("EspressoAncastKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL: Europe.
        /// </summary>
        internal static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must time-travel into the future to use this feature! :).
        /// </summary>
        internal static string FeatureNotImplimented {
            get {
                return ResourceManager.GetString("FeatureNotImplimented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiles all files within a folder into a SARC archive, then compresses the archive with Yaz0..
        /// </summary>
        internal static string FileCompile {
            get {
                return ResourceManager.GetString("FileCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files, {1} bytes.
        /// </summary>
        internal static string FileCount {
            get {
                return ResourceManager.GetString("FileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompresses a Yaz0 file, and if the compressed file is a SARC archive, then it extracts all the files within the archive..
        /// </summary>
        internal static string FileDecompile {
            get {
                return ResourceManager.GetString("FileDecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        internal static string FolderAdd {
            get {
                return ResourceManager.GetString("FolderAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder.
        /// </summary>
        internal static string FolderOpen {
            get {
                return ResourceManager.GetString("FolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        internal static string FolderSelect {
            get {
                return ResourceManager.GetString("FolderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Game Database.
        /// </summary>
        internal static string GameDatabaseDelete {
            get {
                return ResourceManager.GetString("GameDatabaseDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Game Database.
        /// </summary>
        internal static string GameDatabaseExport {
            get {
                return ResourceManager.GetString("GameDatabaseExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game database was generated by a newer version of Uwizard. It may be incompatible..
        /// </summary>
        internal static string GameDatabaseGeneratedNewer {
            get {
                return ResourceManager.GetString("GameDatabaseGeneratedNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Game Database.
        /// </summary>
        internal static string GameDatabaseImport {
            get {
                return ResourceManager.GetString("GameDatabaseImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Game Files.
        /// </summary>
        internal static string GameFilesExtract {
            get {
                return ResourceManager.GetString("GameFilesExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Information.
        /// </summary>
        internal static string GameInformation {
            get {
                return ResourceManager.GetString("GameInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This permanently deletes all information about all games..
        /// </summary>
        internal static string GameInformationDelete {
            get {
                return ResourceManager.GetString("GameInformationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete all information about all games?.
        /// </summary>
        internal static string GameInformationDeleteConfirm {
            get {
                return ResourceManager.GetString("GameInformationDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game Information.
        /// </summary>
        internal static string GameInformationSave {
            get {
                return ResourceManager.GetString("GameInformationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves any modifications to the game information (like inputting the title key) to a permanent record..
        /// </summary>
        internal static string GameInformationSaveInformation {
            get {
                return ResourceManager.GetString("GameInformationSaveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game list is up to date..
        /// </summary>
        internal static string GameListUpToDate {
            get {
                return ResourceManager.GetString("GameListUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is not in the database. Please enter the name:.
        /// </summary>
        internal static string GameNotInDatabase {
            get {
                return ResourceManager.GetString("GameNotInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0:game:games} added and {1} {1:game:games} updated from gametdb.com.
        /// </summary>
        internal static string GameTBDAddUpdate {
            get {
                return ResourceManager.GetString("GameTBDAddUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted at wiiubrew.net.
        /// </summary>
        internal static string Hosted {
            get {
                return ResourceManager.GetString("Hosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hex String.
        /// </summary>
        internal static string InvalidHex {
            get {
                return ResourceManager.GetString("InvalidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Wii U disc Image. Perhaps you forgot to unzip the file?.
        /// </summary>
        internal static string InvalidWiiUDisk {
            get {
                return ResourceManager.GetString("InvalidWiiUDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC: Japan.
        /// </summary>
        internal static string JPN {
            get {
                return ResourceManager.GetString("JPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Key.
        /// </summary>
        internal static string KeyImport {
            get {
                return ResourceManager.GetString("KeyImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Keys.
        /// </summary>
        internal static string KeysDeleteAll {
            get {
                return ResourceManager.GetString("KeysDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete all keys including title keys?.
        /// </summary>
        internal static string KeysDeleteAllConfirm {
            get {
                return ResourceManager.GetString("KeysDeleteAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All keys have been succesfully deleted!.
        /// </summary>
        internal static string KeysDeleteAllSuccess {
            get {
                return ResourceManager.GetString("KeysDeleteAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Keys.
        /// </summary>
        internal static string KeysHide {
            get {
                return ResourceManager.GetString("KeysHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a language for Uwizard..
        /// </summary>
        internal static string LanguageSelect {
            get {
                return ResourceManager.GetString("LanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Local File, Skipping....
        /// </summary>
        internal static string LocalFileSkip {
            get {
                return ResourceManager.GetString("LocalFileSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This permanently deletes all Nintendo-Proprietary keys including title keys..
        /// </summary>
        internal static string NintendoKeyDelete {
            get {
                return ResourceManager.GetString("NintendoKeyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides all Nintendo-proprietary keys from non-active boxes..
        /// </summary>
        internal static string NintendoKeyHide {
            get {
                return ResourceManager.GetString("NintendoKeyHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no compatible sound files in the selected directory!.
        /// </summary>
        internal static string NoCompatableSoundFiles {
            get {
                return ResourceManager.GetString("NoCompatableSoundFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Key Entered.
        /// </summary>
        internal static string NoKey {
            get {
                return ResourceManager.GetString("NoKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SHA1 Available.
        /// </summary>
        internal static string NoSHA1 {
            get {
                return ResourceManager.GetString("NoSHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUS Downloader U.
        /// </summary>
        internal static string NUSDownloaderU {
            get {
                return ResourceManager.GetString("NUSDownloaderU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting NUS Download. Please be patient!.
        /// </summary>
        internal static string NUSDownloading {
            get {
                return ResourceManager.GetString("NUSDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUS Download Finished..
        /// </summary>
        internal static string NUSDownloadSuccess {
            get {
                return ResourceManager.GetString("NUSDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list provides an easy way to choose NUS titles to download..
        /// </summary>
        internal static string NUSTitleDownload {
            get {
                return ResourceManager.GetString("NUSTitleDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUS title ID. This MUST be 16 characters long..
        /// </summary>
        internal static string NUSTitleID {
            get {
                return ResourceManager.GetString("NUSTitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUS title version. If this is left blank, then the latest version will be downloaded..
        /// </summary>
        internal static string NUSTitleVersion {
            get {
                return ResourceManager.GetString("NUSTitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening output directory....
        /// </summary>
        internal static string OpeningOutputDirectory {
            get {
                return ResourceManager.GetString("OpeningOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading .
        /// </summary>
        internal static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiles all files within a folder into a SARC archive..
        /// </summary>
        internal static string SARCCompile {
            get {
                return ResourceManager.GetString("SARCCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracts all the files within a SARC archive..
        /// </summary>
        internal static string SARCExtract {
            get {
                return ResourceManager.GetString("SARCExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting SARC archive!.
        /// </summary>
        internal static string SARCExtractError {
            get {
                return ResourceManager.GetString("SARCExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SARC Archives|*.sarc|All Files|*.*.
        /// </summary>
        internal static string SARCFileType {
            get {
                return ResourceManager.GetString("SARCFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to pack into a SARC archive..
        /// </summary>
        internal static string SARCFolderSelect {
            get {
                return ResourceManager.GetString("SARCFolderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error packing SARC archive!.
        /// </summary>
        internal static string SARCPackError {
            get {
                return ResourceManager.GetString("SARCPackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress SZS.
        /// </summary>
        internal static string SARCSZSCompress {
            get {
                return ResourceManager.GetString("SARCSZSCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress SZS.
        /// </summary>
        internal static string SARCSZSDecompress {
            get {
                return ResourceManager.GetString("SARCSZSDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract SARC.
        /// </summary>
        internal static string SARCSZSExtract {
            get {
                return ResourceManager.GetString("SARCSZSExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress and Extract SARC.SZS.
        /// </summary>
        internal static string SARCSZSExtractDecompress {
            get {
                return ResourceManager.GetString("SARCSZSExtractDecompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack SARC.
        /// </summary>
        internal static string SARCSZSPack {
            get {
                return ResourceManager.GetString("SARCSZSPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack and Compress SARC.SZS.
        /// </summary>
        internal static string SARCSZSPackCompress {
            get {
                return ResourceManager.GetString("SARCSZSPackCompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching game database....
        /// </summary>
        internal static string SearchingDatabase {
            get {
                return ResourceManager.GetString("SearchingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching GameTDB for covers....
        /// </summary>
        internal static string SearchingForCovers {
            get {
                return ResourceManager.GetString("SearchingForCovers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the extracted files..
        /// </summary>
        internal static string SelectSaveLocation {
            get {
                return ResourceManager.GetString("SelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file is missing! Your settings and system keys are now lost..
        /// </summary>
        internal static string SettingsMissing {
            get {
                return ResourceManager.GetString("SettingsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified as Correct by SHA1.
        /// </summary>
        internal static string SHA1Correct {
            get {
                return ResourceManager.GetString("SHA1Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified as Incorrect by SHA1.
        /// </summary>
        internal static string SHA1Incorrect {
            get {
                return ResourceManager.GetString("SHA1Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Full Cover.
        /// </summary>
        internal static string ShowFullCover {
            get {
                return ResourceManager.GetString("ShowFullCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Game List.
        /// </summary>
        internal static string ShowGameList {
            get {
                return ResourceManager.GetString("ShowGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to look for sound files..
        /// </summary>
        internal static string SoundFileLocation {
            get {
                return ResourceManager.GetString("SoundFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Files in Selected Folder.
        /// </summary>
        internal static string SoundFilesInFolder {
            get {
                return ResourceManager.GetString("SoundFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Manager.
        /// </summary>
        internal static string SoundManager {
            get {
                return ResourceManager.GetString("SoundManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode a Wii U Sound Stream.
        /// </summary>
        internal static string SoundStreamDecode {
            get {
                return ResourceManager.GetString("SoundStreamDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Wii U Sound Stream to MP3(s).
        /// </summary>
        internal static string SoundStreamDecodeMP3 {
            get {
                return ResourceManager.GetString("SoundStreamDecodeMP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Wii U Sound Stream to WAV(s).
        /// </summary>
        internal static string SoundStreamDecodeWAV {
            get {
                return ResourceManager.GetString("SoundStreamDecodeWAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either this is not a valid Wii U Sound Stream, or the file is in use by another program..
        /// </summary>
        internal static string SoundStreamError {
            get {
                return ResourceManager.GetString("SoundStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Channels Separately.
        /// </summary>
        internal static string SoundStreamExportSeparate {
            get {
                return ResourceManager.GetString("SoundStreamExportSeparate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all the channels from one Wii U Sound Stream to multiple files instead of mixing them into one..
        /// </summary>
        internal static string SoundStreamExportSeparateInformation {
            get {
                return ResourceManager.GetString("SoundStreamExportSeparateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only each individual channel can be converted to MP3. Do you want convert each channel separetely?.
        /// </summary>
        internal static string SoundStreamExportSeparateMP3 {
            get {
                return ResourceManager.GetString("SoundStreamExportSeparateMP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U Sound Streams|*.bfstm;*.bfwav.
        /// </summary>
        internal static string SoundStreamFileType {
            get {
                return ResourceManager.GetString("SoundStreamFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Sound Stream.
        /// </summary>
        internal static string SoundStreamPlay {
            get {
                return ResourceManager.GetString("SoundStreamPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U Starbuck Ancast Key.
        /// </summary>
        internal static string StarbuckAncastKey {
            get {
                return ResourceManager.GetString("StarbuckAncastKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing Encrypted Content....
        /// </summary>
        internal static string StoringEncryptedContent {
            get {
                return ResourceManager.GetString("StoringEncryptedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error compressing SZS file!.
        /// </summary>
        internal static string SZSCompressError {
            get {
                return ResourceManager.GetString("SZSCompressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decompressing SZS file!.
        /// </summary>
        internal static string SZSDecompressError {
            get {
                return ResourceManager.GetString("SZSDecompressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to pack and compress into a SARC.SZS compressed archive..
        /// </summary>
        internal static string SZSFolderSelect {
            get {
                return ResourceManager.GetString("SZSFolderSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files|*.txt|All Files|*.*.
        /// </summary>
        internal static string TextFileType {
            get {
                return ResourceManager.GetString("TextFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Ticket....
        /// </summary>
        internal static string TicketDownload {
            get {
                return ResourceManager.GetString("TicketDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Ticket Failed:.
        /// </summary>
        internal static string TicketDownloadFailed {
            get {
                return ResourceManager.GetString("TicketDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing Ticket....
        /// </summary>
        internal static string TicketParse {
            get {
                return ResourceManager.GetString("TicketParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ticket is required to decrypt the contents, but a ticket for this title is not available on Nintendo&apos;s server. Would you like to select a ticket file to use? The ticket in a Wii U game disc for the same game from NUS is found in \system\\02\\title.tik\..
        /// </summary>
        internal static string TicketSelectConfirmation {
            get {
                return ResourceManager.GetString("TicketSelectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Unavailable.
        /// </summary>
        internal static string TicketUnavailable {
            get {
                return ResourceManager.GetString("TicketUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Title.
        /// </summary>
        internal static string TitleAdd {
            get {
                return ResourceManager.GetString("TitleAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the currently entered title and version to the easy-access list..
        /// </summary>
        internal static string TitleAddInformation {
            get {
                return ResourceManager.GetString("TitleAddInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Title.
        /// </summary>
        internal static string TitleDelete {
            get {
                return ResourceManager.GetString("TitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes all titles from the easy-access list..
        /// </summary>
        internal static string TitleDeleteAllInformation {
            get {
                return ResourceManager.GetString("TitleDeleteAllInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected title from the easy-access list..
        /// </summary>
        internal static string TitleDeleteInformation {
            get {
                return ResourceManager.GetString("TitleDeleteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Title {0} v{1}... {2} [Latest].
        /// </summary>
        internal static string TitleDownloadInformation {
            get {
                return ResourceManager.GetString("TitleDownloadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title ID:.
        /// </summary>
        internal static string TitleID {
            get {
                return ResourceManager.GetString("TitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Key.
        /// </summary>
        internal static string TitleKey {
            get {
                return ResourceManager.GetString("TitleKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Version:.
        /// </summary>
        internal static string TitleVersion {
            get {
                return ResourceManager.GetString("TitleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading TMD....
        /// </summary>
        internal static string TMDDownload {
            get {
                return ResourceManager.GetString("TMDDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading TMD Failed:.
        /// </summary>
        internal static string TMDDownloadFailed {
            get {
                return ResourceManager.GetString("TMDDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing TMD....
        /// </summary>
        internal static string TMDParse {
            get {
                return ResourceManager.GetString("TMDParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        internal static string UpdateCheck {
            get {
                return ResourceManager.GetString("UpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwizard has been updated to version {0}.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwizard has been updated to version {0}, but because of an error in the update process, some of your data may not be intact..
        /// </summary>
        internal static string UpdatedWithError {
            get {
                return ResourceManager.GetString("UpdatedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwizard is up to date!.
        /// </summary>
        internal static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTSC: North America.
        /// </summary>
        internal static string USA {
            get {
                return ResourceManager.GetString("USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwizard has been successfully updated to version {0}, but because of an incompatibility issue, if you updated from version 1.0.0, then your system keys are mangled and need to be re-entered..
        /// </summary>
        internal static string UwizardUpdatePartialSuccess {
            get {
                return ResourceManager.GetString("UwizardUpdatePartialSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading version information from wiiubrew.net. Update process canceled..
        /// </summary>
        internal static string VersionDownloadError {
            get {
                return ResourceManager.GetString("VersionDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAV Sound Files|*.wav|MP3 Sound Files|*.mp3.
        /// </summary>
        internal static string WAVFileType {
            get {
                return ResourceManager.GetString("WAVFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a directory that contains Wii U games to add to this list..
        /// </summary>
        internal static string WiiUGameDirectorySearch {
            get {
                return ResourceManager.GetString("WiiUGameDirectorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wii U Games|*.wud|All Files|*.*.
        /// </summary>
        internal static string WiiUGameFileTypes {
            get {
                return ResourceManager.GetString("WiiUGameFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ID.
        /// </summary>
        internal static string WiiUGameID {
            get {
                return ResourceManager.GetString("WiiUGameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not saved your changes to the current Wii U game&apos;s information. This includes the name and the title key. Do you want to save these changes now?.
        /// </summary>
        internal static string WiiUGameInformationSaveConfirm {
            get {
                return ResourceManager.GetString("WiiUGameInformationSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Name.
        /// </summary>
        internal static string WiiUGameName {
            get {
                return ResourceManager.GetString("WiiUGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Wii U Game.
        /// </summary>
        internal static string WiiUGameOpen {
            get {
                return ResourceManager.GetString("WiiUGameOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrub Wii U Game.
        /// </summary>
        internal static string WiiUGameScrub {
            get {
                return ResourceManager.GetString("WiiUGameScrub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeroes unused data. This allows the backup to be compressed more efficiently using NTFS native compression..
        /// </summary>
        internal static string WiiUGameScrubInformation {
            get {
                return ResourceManager.GetString("WiiUGameScrubInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WUD Manager.
        /// </summary>
        internal static string WUDManager {
            get {
                return ResourceManager.GetString("WUDManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compresses a file with Yaz0..
        /// </summary>
        internal static string Yaz0Compress {
            get {
                return ResourceManager.GetString("Yaz0Compress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is not Yaz0 compressed!.
        /// </summary>
        internal static string Yaz0CompressedFileNot {
            get {
                return ResourceManager.GetString("Yaz0CompressedFileNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaz0 Compressed Files|*.szs|All Files|*.*.
        /// </summary>
        internal static string Yaz0FileTypes {
            get {
                return ResourceManager.GetString("Yaz0FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompresses a Yaz0 file..
        /// </summary>
        internal static string Yazz0Decompress {
            get {
                return ResourceManager.GetString("Yazz0Decompress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
